# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainfrm.ui'
#
# Created: Tue Nov 06 22:24:57 2018
#      by: PyQt4 UI code generator 4.5.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(985, 577)
        Dialog.setMinimumSize(QtCore.QSize(900, 0))
        self.gridLayout = QtGui.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.layout_display = QtGui.QGridLayout()
        self.layout_display.setObjectName("layout_display")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.layout_display.addItem(spacerItem, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.layout_display, 0, 0, 1, 1)
        self.groupBox = QtGui.QGroupBox(Dialog)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.comboBox_amplifier = QtGui.QComboBox(self.groupBox)
        self.comboBox_amplifier.setObjectName("comboBox_amplifier")
        self.comboBox_amplifier.addItem(QtCore.QString())
        self.comboBox_amplifier.addItem(QtCore.QString())
        self.comboBox_amplifier.addItem(QtCore.QString())
        self.comboBox_amplifier.addItem(QtCore.QString())
        self.comboBox_amplifier.addItem(QtCore.QString())
        self.gridLayout_2.addWidget(self.comboBox_amplifier, 1, 1, 1, 2)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 12, 0, 1, 1)
        self.comboBox_samplingrate = QtGui.QComboBox(self.groupBox)
        self.comboBox_samplingrate.setObjectName("comboBox_samplingrate")
        self.comboBox_samplingrate.addItem(QtCore.QString())
        self.comboBox_samplingrate.addItem(QtCore.QString())
        self.comboBox_samplingrate.addItem(QtCore.QString())
        self.comboBox_samplingrate.addItem(QtCore.QString())
        self.gridLayout_2.addWidget(self.comboBox_samplingrate, 2, 1, 1, 1)
        self.textEdit_sigch = QtGui.QTextEdit(self.groupBox)
        self.textEdit_sigch.setMaximumSize(QtCore.QSize(16777215, 90))
        self.textEdit_sigch.setObjectName("textEdit_sigch")
        self.gridLayout_2.addWidget(self.textEdit_sigch, 4, 0, 1, 3)
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 13, 0, 1, 1)
        self.lineEdit_port = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_port.setObjectName("lineEdit_port")
        self.gridLayout_2.addWidget(self.lineEdit_port, 13, 1, 1, 2)
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 1, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.groupBox)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 14, 0, 1, 1)
        self.lineEdit_ip = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_ip.setObjectName("lineEdit_ip")
        self.gridLayout_2.addWidget(self.lineEdit_ip, 12, 1, 1, 2)
        self.textEdit_status = QtGui.QTextEdit(self.groupBox)
        self.textEdit_status.setObjectName("textEdit_status")
        self.gridLayout_2.addWidget(self.textEdit_status, 15, 0, 1, 3)
        self.radioButton_remote = QtGui.QRadioButton(self.groupBox)
        self.radioButton_remote.setObjectName("radioButton_remote")
        self.gridLayout_2.addWidget(self.radioButton_remote, 11, 0, 1, 2)
        self.radioButton_local = QtGui.QRadioButton(self.groupBox)
        self.radioButton_local.setChecked(True)
        self.radioButton_local.setObjectName("radioButton_local")
        self.gridLayout_2.addWidget(self.radioButton_local, 10, 0, 1, 2)
        self.pushButton_loadparm = QtGui.QPushButton(self.groupBox)
        self.pushButton_loadparm.setObjectName("pushButton_loadparm")
        self.gridLayout_2.addWidget(self.pushButton_loadparm, 0, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 3, 0, 1, 3)
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 2, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 5, 0, 1, 1)
        self.pushButton_saveparm = QtGui.QPushButton(self.groupBox)
        self.pushButton_saveparm.setObjectName("pushButton_saveparm")
        self.gridLayout_2.addWidget(self.pushButton_saveparm, 0, 2, 1, 1)
        self.label_9 = QtGui.QLabel(self.groupBox)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 8, 0, 1, 1)
        self.textEdit_exparm = QtGui.QTextEdit(self.groupBox)
        self.textEdit_exparm.setObjectName("textEdit_exparm")
        self.gridLayout_2.addWidget(self.textEdit_exparm, 9, 0, 1, 3)
        self.textEdit_refch = QtGui.QTextEdit(self.groupBox)
        self.textEdit_refch.setMaximumSize(QtCore.QSize(16777215, 30))
        self.textEdit_refch.setObjectName("textEdit_refch")
        self.gridLayout_2.addWidget(self.textEdit_refch, 6, 0, 1, 3)
        self.pushButton_eegacq = QtGui.QPushButton(self.groupBox)
        self.pushButton_eegacq.setObjectName("pushButton_eegacq")
        self.gridLayout_2.addWidget(self.pushButton_eegacq, 16, 2, 1, 1)
        self.pushButton_impedance = QtGui.QPushButton(self.groupBox)
        self.pushButton_impedance.setObjectName("pushButton_impedance")
        self.gridLayout_2.addWidget(self.pushButton_impedance, 16, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 0, 1, 1, 1)

        self.retranslateUi(Dialog)
        
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_amplifier.setItemText(0, QtGui.QApplication.translate("Dialog", "actichamp", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_amplifier.setItemText(1, QtGui.QApplication.translate("Dialog", "emotive_epoc", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_amplifier.setItemText(2, QtGui.QApplication.translate("Dialog", "simulator", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_amplifier.setItemText(3, QtGui.QApplication.translate("Dialog", "DSI-24", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_amplifier.setItemText(4, QtGui.QApplication.translate("Dialog", "neurosky", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "IP", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_samplingrate.setItemText(0, QtGui.QApplication.translate("Dialog", "200", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_samplingrate.setItemText(1, QtGui.QApplication.translate("Dialog", "500", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_samplingrate.setItemText(2, QtGui.QApplication.translate("Dialog", "1000", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_samplingrate.setItemText(3, QtGui.QApplication.translate("Dialog", "2000", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Dialog", "port", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "放大器选择", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Dialog", "状态：", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_remote.setText(QtGui.QApplication.translate("Dialog", "远程发射信号", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_local.setText(QtGui.QApplication.translate("Dialog", "本地发射信号", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_loadparm.setText(QtGui.QApplication.translate("Dialog", "加载参数", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "信号通道 例：1-10,12 (以逗号分隔)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Dialog", "采样率：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "参考通道", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_saveparm.setText(QtGui.QApplication.translate("Dialog", "保存参数", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Dialog", "扩展参数", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_eegacq.setText(QtGui.QApplication.translate("Dialog", "EEG采集", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_impedance.setText(QtGui.QApplication.translate("Dialog", "阻抗检测", None, QtGui.QApplication.UnicodeUTF8))

